name: Latest stable version compatibility with Quarkus

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-provider: [ "jackson-classic", "jsonb-classic", "jackson-reactive", "jsonb-reactive" ]
        quarkus-version: [ "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Integration Tests (latest - classic - jackson)
        env:
          LATEST_STABLE_EXTENSION_VERSION: "3.7.0"
        run: |
          echo "Checking quarkus-resteasy-problem $LATEST_STABLE_EXTENSION_VERSION with Quarkus v${{ matrix.quarkus-version }}"
          ./mvnw clean verify \
              -P${{ matrix.json-provider }},quarkus-${{ matrix.quarkus-version }} \
              -pl integration-test \
              -Dquarkus-resteasy-problem.version=$LATEST_STABLE_EXTENSION_VERSION