name: Regression Tests

on:
  push:
    branches: [ master, v3.X, v2.X, v1.X ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        quarkus-version: [ "3.0", "3.1", "3.2", "3.3", "3.4", "3.5" ]
        json-provider: [ "jsonb-classic", "jackson-classic" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Build project
        run: ./mvnw install -Pquick -pl '!integration-test'

      - name: Integration tests
        run: |
          ./mvnw clean verify \
              -P${{ matrix.json-provider }},quarkus-${{ matrix.quarkus-version }} \
              -pl integration-test
