name: Quickstart Flow Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-provider: [ "resteasy-jsonb", "resteasy-jackson" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Compile and Install Extension
        run: |
          ./mvnw install -Pquick -pl '!integration-test'
          mkdir quickstart

      - name: Generate Quickstart App
        working-directory: ./quickstart
        run: |
          QUARKUS_VERSION=$(mvn -f ../pom.xml -q -Dexec.executable=echo -Dexec.args='${quarkus.version}' --non-recursive exec:exec)
          echo "QUARKUS_VERSION = $QUARKUS_VERSION"

          mvn io.quarkus:quarkus-maven-plugin:$QUARKUS_VERSION:create \
            -Dextensions="resteasy,${{ matrix.json-provider }}" \
            -DprojectGroupId=problem \
            -DprojectArtifactId=quarkus-resteasy-problem-playground \
            -DclassName="problem.HelloResource" \
            -Dpath="/hello"

          EXTENSION_VERSION=$(mvn -f ../pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "EXTENSION_VERSION = $EXTENSION_VERSION"
          cd quarkus-resteasy-problem-playground
          ./mvnw quarkus:add-extension -Dextensions="io.quarkiverse.resteasy-problem:quarkus-resteasy-problem:$EXTENSION_VERSION"

      - name: Run tests
        working-directory: ./quickstart/quarkus-resteasy-problem-playground
        run: |
          ./mvnw --no-transfer-progress test